name: Build and Push to ECR Public

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: public.ecr.aws/k9l6i6n0  
  IMAGE_NAME: nd/ecr-repo
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR Public
      run: |
        aws ecr-public get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin public.ecr.aws

    - name: Build Docker image
      run: docker build -t $IMAGE_NAME .

    - name: Tag image for ECR Public
      run: docker tag $IMAGE_NAME:latest $ECR_REGISTRY/$IMAGE_NAME:latest

    - name: Push image to ECR Public
      run: docker push $ECR_REGISTRY/$IMAGE_NAME:latest
